#pragma once

#include <pluginterfaces/base/fplatform.h>
#include "projectversion.h" // generated by cmake

#define stringPluginName		"Basic"

#define stringOriginalFilename	"basic.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	stringPluginName" VST3-SDK (64Bit)"
#else
#define stringFileDescription	stringPluginName" VST3-SDK"
#endif
#define stringCompanyWeb		"http://www.qt.io"
#define stringCompanyEmail		"mailto:info@ddob.de"
#define stringCompanyName		"@DDob"
#define stringLegalCopyright	"� 2022 Steinberg Media Technologies"
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
